# Generated by Django 4.1.7 on 2023-03-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField()),
                ('start_day', models.PositiveIntegerField()),
                ('end_day', models.PositiveIntegerField()),
            ],
            options={
                'unique_together': {('profile', 'order')},
            },
        ),
    ]
